### ISSUE TITLE
How env.get_indi_terminated() function defined?

### ISSUE THREAD

**Issue by RZ-Q** [cathyhxh/DIFFER#1]
In episode_runner.py
post_transition_data = {
              "actions": actions,
              "reward": [(reward,)],
              "terminated": [(terminated != env_info.get("episode_limit", False),)],
              "indi_terminated": [self.env.get_indi_terminated()]
          }
There is an function called env.get_indi_terminated(), but the original SMAC env doesn't has this function.
How to judge a individual is terminated?

**Comment by cathyhxh** [comment]
The termination of the individual experience transpires upon the agent's death.
Please substitute "SMAC_PATH/env/starcraft2/starcraft2.py" with the file "starcraft2.py" within this repository.
In this particular version of "starcraft2.py" we have delineated the function "get_indi_terminated()" on Line 1714.

**Comment by RZ-Q** [comment]
Thank answer
